"""
Django settings for genbioconsortium project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-92cz!u&2wm0wx*v*u+3o4jgu=$v&j^i#$tg9gfp_n(7x+*qj#u'

import sys
import os




# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', '770b-197-232-61-198.in.ngrok.io']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #add the user app
    'users',
    'crispy_forms',
    'crispy_bootstrap4',
    'django_daraja',
    #'django_daraja',
    'payment',
    'django_bootstrap_icons',
    'captcha',
    'paypal.standard.ipn',
    'membership',
    

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'genbioconsortium.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'genbioconsortium.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'consortium',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        
    }
}





# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL='/static/'
# STATIC_ROOT=os.path.join(BASE_DIR, 'static/')
MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR, 'media/')
#Remove this line before production
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_TEMPLATE_PACK = 'bootstrap4'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'profile'
LOGOUT_REDIRECT_URL = 'login'


# Emailing settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_FROM = 'Nelson.masibo.kenyaweb.com'
EMAIL_HOST_USER = 'kenyawebapps87@gmail.com'
EMAIL_HOST_PASSWORD = 'pzjotxvpakzrzlhi'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

PASSWORD_RESET_TIMEOUT = 14400
#mpesa payment details
consumer_key = "piumJBdCtSxo6GX9p8j8kqcljVJNXJMA"
consumer_secret = "pd7cx9QgbZReJdZ1"

PAYPAL_CLIENT_ID = 'AYl37zK_CtsjR1OHczWeJInSWmDcajP2ub797KQ4hzOTlH_obTpf_DSwhy0aZnQJA_aEk87sdy6S8SiE'
PAYPAL_SECRET = 'ELb18aC8JDFp2oQOYOcXhpmifN7YH92gncYnmJ4-JC9sNHl6yFBcdeK-n9_pHKGxtSKBLlZueiOs4GZw'
access_token = 'A21AALNkoORiuidEGM79ifl5yU6IyO53ZZCWGzhiWDL6U4MQtuGfcvl3YUhwXLlXJ1ruC1nBVlkLlxImJEmOF0fE1Rnl3bR9Q","token_type":"Bearer","app_id":"APP-80W284485P519543T'
PAYPAL_RECEIVER_EMAIL = 'neilahmasibo@gmail.com'
PAYPAL_TEST = True



RECAPTCHA_PUBLIC_KEY = '6LcV3RQlAAAAANRWtvANODusNIRKJg61r8PR-uK-'
RECAPTCHA_PRIVATE_KEY = '6LcV3RQlAAAAADkIkGLs9X2Gb5Z7hK3y7Ayd7lQ-'
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']



SECURE_CROSS_ORIGIN_OPENER_POLICY='same-origin-allow-popups'