# Generated by Django 4.1.7 on 2023-05-07 14:13

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipregistration',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
