# Generated by Django 4.1.7 on 2023-05-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_membershipregistration_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipregistration',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
