# Generated by Django 4.2.1 on 2023-05-10 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_membershipregistration_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=60)),
                ('membership_type', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('payment_status', models.CharField(max_length=30)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paypal_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payer_id', models.CharField(max_length=100)),
                ('membership_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membershipregistration')),
            ],
        ),
    ]
