# Generated by Django 4.2.1 on 2023-07-10 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipregistration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
