# Generated by Django 4.2.1 on 2023-07-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_membershipregistration_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='registration_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
