# Generated by Django 4.2.1 on 2023-07-10 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('precongress', '0002_precongressregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='precongressregistration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
